apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirmation
  labels:
    app: confirmation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confirmation
  template:
    metadata:
      labels:
        app: confirmation
    spec:
      containers:
        - name: confirmation
          image: username/confirmation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5